### ISSUE TITLE
Installation Instructions are too vague

### ISSUE THREAD

**Issue by Bi0force1** [hankhank10/Python-SimConnect#1]
I am happy to test out your app, but i have no python knowledge.
I installed python 3.8, and can open it, but i am not able to use Python or Windows CMD to do the "pip install flask" command.

if you make the instructions easier to follow for a rookie, my friends and i are looking for apps like this to test.

**Comment by ip999** [comment]
If you're failing at that stage there is likely some issue with your python installation, pip should be included in the standard python package. Maybe check your PATH is correct, or see here for some more ideas... 
https://stackoverflow.com/questions/39832219/pip-not-working-in-python-installation-in-windows-10

**Comment by DownInTheShop** [comment]
I have some experience with python, and was able to get the cockpit companion running based on the instructions. I still can't get python-simconnect going for whatever reason though. I'm all for hand-holding step by step instructions for running things like this, but this is still pretty early in development.

What error do you get when type "pip install flask"?

**Comment by Bi0force1** [comment]
@ip999 ,  Thanks for those instructions.  I was able to install pip and flask. 

Unfortunately, I cant get the rest of this app to work do to my lack of knowledge on python.
I'll close this comment out, I think I am not the target audience for this app.

**Comment by ip999** [comment]
> @ip999 ,  Thanks for those instructions.  I was able to install pip and flask. 
> 
> 
> 
> Unfortunately, I cant get the rest of this app to work do to my lack of knowledge on python.
> 
> I'll close this comment out, I think I am not the target audience for this app.

I don't accept defeat easily, we can get this sorted for you. Let us know what step you're on and exactly the error you're seeing, this will be solvable.
