### ISSUE TITLE
Tool Running Issue

### ISSUE THREAD

**Issue by Swappea** [hankhank10/Python-SimConnect#2]
I cloned the repository locally. I did pip install flask.
But whenever I try to run "python .\glass_server.py", I get following error.

OSError: [WinError 193] %1 is not a valid Win32 application

![image](https://user-images.githubusercontent.com/28304828/92937150-99a93200-f468-11ea-8947-08496099f737.png)

**Comment by odessadraekavik** [comment]
Hello @Swappea 
You need to use the 64bit version of Python.

You can download the right version to use here : https://www.python.org/ftp/python/3.8.6/python-3.8.6rc1-amd64.exe

(Do not forget to install Flask and SimConnect after reinstalling Python)

**Comment by Swappea** [comment]
Thank you. I was using 32bit version(I dont know how).
It did worked after installing 64bit.
But I made some changes in the code and increased the setInterval time to 1 second then it lead to exceptions on the python server side. Any idea on this errors?
